feat: add notable contribution template
gnolang/game-of-realms pull request #22
Opened 2024-11-01 14:13 UTC by Kouteki

Add

- Simple issue template
- Notable contribution template

2024-12-12 18:52 UTC, leohhhn approved these changes

2025-01-10 15:36 UTC, moul commented on .github/ISSUE_TEMPLATE/SIMPLE-ISSUE.md
> +---
what's the advantage of having such template?

2025-01-10 15:39 UTC, moul commented on .github/ISSUE_TEMPLATE/NOTABLE-CONTRIBUTION.md
> +---
I think we should use PRs only for notable contributions and discussions about their relevance.

A notable contribution should consist of a clear and concise commit title, ideally a single explicit line. Sometimes, it may need to include several links, but the main description should be in the actual contributions, such as the PR in the monorepo. A notable contribution entry here should not be the place where we spend too much time explaining why we believe it is significant.

If we want discussions, they can occur on the PR discussion page.

2025-01-10 15:40 UTC, moul requested changes
Blocking until someone convince me why an issue-based approach might be better.

2025-02-25 13:14 UTC, Kouteki commented
Closing - the template is not compatible with what the team wants to accomplish

2025-02-25 13:14 UTC, closed without merging